services:
  postgres:
    image: postgres:latest
    container_name: postgres_dev
    env_file:
      - server/.env      
    ports:
      - "5432:5432"                   
    volumes:
      - postgres_data:/var/lib/postgresql/data  

volumes:
  postgres_data:  